### PR TITLE
Add deepspeech-win-b worker type and include cudafe++.exe patching

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by reuben** [comment]
@lissyx

**Comment by petemoore** [comment]
I can deploy this tomorrow - need to head out now, sorry!

**Comment by reuben** [comment]
No problem! Please let me know when it's deployed.

**Comment by reuben** [comment]
@petemoore friendly ping. Have you been able to deploy this?

**Comment by petemoore** [comment]
@reuben I'm so sorry, I took Friday off, and completely forgot. I'm deploying it now!

**Comment by reuben** [comment]
No worries. And thanks!

**Comment by petemoore** [comment]
@reuben Deployment completed!

**Comment by reuben** [comment]
\o/ thanks!

**Pull request merged**
