### PR TITLE
Bug 1181524 - resolve with malformed-payload if artifact.expires < task.deadline

### PR DESCRIPTION
**Pull request by petemoore**
Should probably add some tests...

### CODE REVIEW

**Comment by petemoore** [comment]
I should also add an artifact with an explanation of why the task resolved with malformed-payload...

**Comment by gregarndt** [comment]
Hrm, with docker-worker we just put the error int he task log.  Woudn't the error just be added to that unified log you create at the end or does it now create that in the case the commands don't run at all?

**Comment by petemoore** [comment]
Good point, thanks Greg! Then I can name the artifact `public/logs/live_backing.log`. Then it is consistent with the other logs (e.g. for treeherder-parsing). In this case there won't be a livelog, but I don't think that matters too much. (Note, the GW only creates the log artifacts if the task runs, which it won't for a malformed-payload, so this shouldn't conflict with any logs the GW would otherwise create).

**Comment by jonasfj** [comment]
An error in the task log would be ideal... but as reporting `malformed-payload` is the most important thing... r+

**Pull request merged**
