### PR TITLE
Initial webhooktunnel integration

### PR DESCRIPTION
**Pull request by ckousik**
This commit sets up logging using webhooktunnel. This is done by creating a webhookserver instance. The `WebhookLogTask` (`TaskFeature`) can use the WebhookServer to add handlers at specific URLs. Logs are streamed through these urls.

### CODE REVIEW

**Comment by ckousik** [comment]
@petemoore The tests are passing locally but the travis build is not configured to run the tests that require tc credentials.

**Comment by petemoore** [comment]
@ckousik Many thanks for this! I see the tests have been removed, but really I'd like to have the tests in there. The travis build is configured to run with tc credentials, but it could be that some additional scopes are needed. The scopes the tests currently have are defined [here](https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Ageneric-worker-tester).

Currently they have:

```
    assume:worker-id:test-worker-group/test-worker-id
    assume:worker-type:test-provisioner/*
    generic-worker:cache:banana-cache
    generic-worker:cache:devtools-app
    generic-worker:cache:test-modifications
    generic-worker:cache:unknown-issuer-app-cache
    generic-worker:os-group:abc
    generic-worker:os-group:def
    queue:claim-work:test-provisioner/*
    queue:create-artifact:SampleArtifacts/_/X.txt
    queue:create-artifact:public/logs/live.log
    queue:create-artifact:public/logs/live_backing.log
    queue:create-artifact:public/logs/worker_type_metadata.json
    queue:create-task:test-provisioner/*
    queue:get-artifact:SampleArtifacts/_/X.txt
    queue:get-artifact:SampleArtifacts/b/c/d.jpg
    queue:get-artifact:public/logs/all_commands.log
    queue:get-artifact:public/logs/command_000000.log
    queue:poll-task-urls
    queue:resolve-task
    queue:worker-id:test-worker-group/*
```

You may already be able to update this role to add the missing scopes, but if that doesn't work, can you let me know which scopes need to be added?

Many thanks, and sorry for the delay!

Pete

**Comment by ckousik** [comment]
@petemoore The scope `auth:webhooktunnel` is required using webhooktunnel.

**Comment by petemoore** [comment]
> @petemoore The scope auth:webhooktunnel is required using webhooktunnel.

@ckousik I've added the scope `auth:webhooktunnel` to role [`project:taskcluster:generic-worker-tester`](https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Ageneric-worker-tester). I've resolved the merge conflict with master.

**Comment by ckousik** [comment]
@petemoore should I close this PR?

**Comment by djmitche** [comment]
Done in other PRs.. I forgot this was still open!

**Pull request closed without merging**
